### ISSUE TITLE
Supporting multiple environments

### ISSUE THREAD

**Issue by antgel** [n3integration/terraform-godaddy#14]
Say I have multiple environment support in a traditional terraform pattern. Each environment is in a directory, and has two servers, puppet master and jenkins master.
```
sandbox
- puppet.tf
- jenkins.tf
staging
- puppet.tf
- jenkins.tf
production
- puppet.tf
- jenkins.tf
```

I want my sandbox puppet master A record to map to `puppet.sandbox.example.com`, and my production puppet master A record to map to `puppet.production.example.com`, etc.

Is this module able to support such a use case? It seems that `resource "godaddy_domain_record"` needs to be a monolith, so I can't include more than one for a given domain (in this case `example.com`). It's also not clear if it would work inside a module, modules are for creating multiple instances of given abstractions.

If such usage is supported, what would the pattern look like?

**Comment by n3integration** [comment]
Hey @antgel - Although I haven't explicitly tried to use this provider in a module, it should be supported. Another alternative would be to create a `map` variable and an `env` variable, using the value of `env` as an index into the map. For example:

```
variable "env" {
  default = "sandbox"
}
variable "domain_name" {
  type = "map"
  default = {
    "sandbox":    "puppet.sandbox.example.com",
    "staging":    "puppet.staging.example.com",
    "production": "puppet.production.example.com"
  }
}
resource "godaddy_domain_record" "puppet_domain" {
  "domain": "${lookup(var.domain_name, var.env)}"
  ...
}
```

**Comment by antgel** [comment]
Thanks for the response. I'm still not sure how the above would support multiple enviroments, but we moved to Route 53 in any case, so I might as well close this.

**Comment by Jack64** [comment]
Hi @n3integration,

I was trying the approach you suggested by prepending the "environment prefix" to the domain, but I get a 404 error from GoDaddy saying `Domain staging.example.com not found for shopper` , while the `godaddy_domain_record` for domain `example.com` works correctly.

I'm trying to move from the monolithic `godaddy_domain_record` for `example.com` with all the imported records from my domain to something that creates and removes DNS records in unison with the rest of the terraform configuration for a particular environment. This is a lot harder to do with a monolith than being able to add a `godaddy_domain_record` resource that only manages a subset of records for a particular environment.

Can you please explain what I'm doing wrong? Thanks!

**Comment by n3integration** [comment]
Hey @Jack64 - Thank you for your question. Could you provide additional context?  In the example above, I included a rough plan of how to extract a `godaddy_domain_record` into a module by providing a mapping of environments to domains.

**Comment by phenry20** [comment]
Hi @n3integration. Let me start off by saying thank you for making this plugin. It has worked great for me so far, but the biggest issue I'm having is with multiple environments that share the same domain. 

I have two environments: staging and production and both use the same domain: example.com. 

In the staging environment I want to add an A record to the "staging" subdomain. Ex: staging.example.com 

In the production environment I want to add an A record to the top level domain. Ex: example.com. 

The problem is that your plugin works as an all or nothing approach and deletes everything that's not listed. Therefore when I run the production environment, I lose all the records set in the staging environment and vice versa. 

Is it possible for you to add a variable that allows us to set whether we augment the existing data or delete it?

Thanks
