### ISSUE TITLE
attempting to add a new record wipes entires domain

### ISSUE THREAD

**Issue by ryanmickler** [n3integration/terraform-godaddy#8]
I was trying to use this to add a single record to my dns table, and i got it to add this record, however, in the process it removed all other records from the dns table, (expect the two name servers and the new A entry). is this expected?

**Comment by n3integration** [comment]
Hey @ryanmickler, thanks for dropping by and reaching out about your issue. In short, yes, this is expected behavior. Your terraform configuration should provide the end-state of the dns table. Any delta between your configuration and the current state of the dns table is removed. 

In the future, to perform a dryrun, execute `terraform plan` to determine what changes will be made before running `terraform apply`. If you feel like this sufficiently answers your question, please close out the issue. Thanks again.

**Comment by scream314** [comment]
This gave me a pleasant few hours, too.
Could you please at least emphasize this in the `README` (or accept my PR...)? Please?
(I do not rant, because using other people's free stuff is always risky, and I should have taken precaution, and I was retarded, but... what the fluff?)

**Comment by steveetm** [comment]
IMO this is *not* expected, no way that someone in terraform world should expect that from a provider by default.

**Comment by n3integration** [comment]
@ryanmickler - I've updated the documentation to help prevent this from happening to others. Please feel free to close out the issue, or let me know whether you have any additional concerns.

**Comment by antgel** [comment]
Hi, even after skimming the docs I had wondered if this would be an issue (wiping), and I only came across this issue by chance whilst trying to debug something else. Hence I still don't think the docs are clear enough on this, because they don't explicitly mention the possibility of a destructive operation, which is unusual in the Terraform world. Please consider being more explicit e.g. *NB If your zone contains existing data, please ensure that your Terraform config includes all existing records, otherwise they will be removed.*

Running `terraform plan` does not reflect this - here's what I see when trying to add an A record to a domain that contains other several records:
```antony@tuxrocks:~/terraform$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_instance.puppet: Refreshing state... (ID: i-065f3c26ad3bffceb)
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

  + godaddy_domain_record.puppet-domain
      customer:               "FOO"
      domain:                 "BAR.com"
      record.#:               "1"
      record.1502406454.data: "172.31.53.238"
      record.1502406454.name: "puppet"
      record.1502406454.ttl:  "60"
      record.1502406454.type: "A"


Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by n3integration** [comment]
@antgel - I appreciate your additional feedback on the issue. In the spirit of Infrastructure as Code, and in an optimal case the contents of the resource(s) defined in your Terraform configuration file would have the complete state of each resource. This is the reason behind the design decision where the default behavior is to blindly replace all existing values, but I can completely understand how this may be an issue in some cases.

**Comment by n3integration** [comment]
I've updated the docs and incorporated support for Terraform's import feature. I hope that this clears up any confusion in the future. If this works for you, please close out the issue. If not, I am open to suggestions.

**Comment by antgel** [comment]
Absolutely superb! Thanks! :)

**Comment by ryanmickler** [comment]
thanks a lot!
